-- Seed data for skills table
-- Run this file to populate skills for profile selection

INSERT IGNORE INTO skills (skill_name) VALUES
('Python'),
('JavaScript'),
('TypeScript'),
('React'),
('Angular'),
('Vue.js'),
('Node.js'),
('Flask'),
('Django'),
('FastAPI'),
('Java'),
('C++'),
('C#'),
('Go'),
('Rust'),
('SQL'),
('MongoDB'),
('PostgreSQL'),
('MySQL'),
('Redis'),
('AWS'),
('Azure'),
('Google Cloud'),
('Docker'),
('Kubernetes'),
('Git'),
('Linux'),
('Machine Learning'),
('Deep Learning'),
('Data Science'),
('TensorFlow'),
('PyTorch'),
('NLP'),
('Computer Vision'),
('HTML/CSS'),
('Bootstrap'),
('Tailwind CSS'),
('REST API'),
('GraphQL'),
('Microservices'),
('CI/CD'),
('Agile'),
('Scrum'),
('Project Management'),
('UI/UX Design'),
('Figma'),
('Adobe XD'),
('Communication'),
('Problem Solving'),
('Leadership');
